# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Function App Only
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
# ------------------------------------------------------------------------------------------------------------------------
name: 3.build.deploy.function
run-name: '3 - Build & Deploy Function: ${{ inputs.deployEnvironment }} by @${{ github.actor }}'

on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: Environment
        default: 'dev' 
        type: environment
      runSecurityScan:
        description: Run Security Scan
        default: false
        type: boolean
      runBuild:
        description: Build App
        default: true
        type: boolean
      runDeploy:
        description: Deploy App
        default: true
        type: boolean
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

# ------------------------------------------------------------------------------------------------------------------------
permissions:
  id-token: write
  contents: write
  actions: read
  pages: write
  security-events: write
  checks: write
  issues: read
  pull-requests: read
  packages: read

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  scan-code:
    name: Scan Source Code
    uses: ./.github/workflows/template-scan-code.yml
    secrets: inherit
    if: inputs.runSecurityScan
    with:
      runMSDevSecOpsScan: ${{ inputs.runSecurityScan }}
      runGHASScan: ${{ inputs.runSecurityScan }}

# ------------------------------------------------------------------------------------------------------------------------
  build-app:
    name: Build Function App
    uses: ./.github/workflows/template-function-app-build.yml
    if: inputs.runBuild || inputs.runDeploy
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      rootDirectory: '${{ vars.FUNCTION_APP_PROJECT_FOLDER_NAME }}'
      projectName: '${{ vars.FUNCTION_APP_PROJECT_NAME }}'
      testDirectory: '${{ vars.FUNCTION_APP_TEST_FOLDER_NAME }}'
      testProjectName: '${{ vars.FUNCTION_APP_TEST_PROJECT_NAME }}'
      testApplication: true
      listFilesAfterBuild: true

# ------------------------------------------------------------------------------------------------------------------------
  deploy-app:
    name: Deploy App
    uses: ./.github/workflows/template-function-app-deploy.yml
    if: inputs.runDeploy
    needs: build-app
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      